### ISSUE TITLE
Azure 'service info' displays nothing useful.

### ISSUE THREAD

**Issue by reidjc** [ernestio/ernest#526]
Azure `service info` should show the following when those components exist:
```
Load balancer:
+--------+----------------------------------------------+
|  NAME  |                      IP                      |
+--------+----------------------------------------------+

SQL database:
+--------+----------------------------------------------+
|  NAME  |                 SERVER NAME                  |
+--------+----------------------------------------------+

Instances:
+--------+-----------+------------+
|  NAME  | PUBLIC IP | PRIVATE IP |
+--------+-----------+------------+
```

**Comment by adriacidre** [comment]
Fixed on 
- https://github.com/ernestio/ernest-cli/pull/87
- https://github.com/ernestio/api-gateway/pull/66

**Comment by reidjc** [comment]
Load balancer and SQL database information still not being displayed.
```
➜  demo ernest service apply az3.yml
Environment creation requested
Ernest will show you all output from your requested service creation
You can cancel at any moment with Ctrl+C, even the service is still being created, you won't have any output
Applying your definition
 Created Resource Group az-test
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test
   Status : completed
 Created Virtual Network net
   Address Space : 10.0.0.0/16
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/virtualNetworks/net
   Status : completed
 Created Public IP web-1-config1
   IP : 52.233.137.179
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/publicIPAddresses/web-1-config1
   Status : completed
 Created Public IP web-2-config1
   IP : 52.232.44.210
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/publicIPAddresses/web-2-config1
   Status : completed
 Created Public IP lb-lbip
   IP : 52.232.45.57
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/publicIPAddresses/lb-lbip
   Status : completed
 Created SQL Server jasonr3labs
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Sql/servers/jasonr3labs
   Status    : completed
 Created Storage Account r3labssa1
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Storage/storageAccounts/r3labssa1
   Status    : completed
 Created Subnet sub1
   Address Prefix : 10.0.1.0/24
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/virtualNetworks/net/subnets/sub1
   Status : completed
 Created Subnet sub2
   Address Prefix : 10.0.2.0/24
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/virtualNetworks/net/subnets/sub2
   Status : completed
 Created Loadbalancer lb
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/loadBalancers/lb
   Status    : completed
 Created SQL Database mydb
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Sql/servers/jasonr3labs/databases/mydb
   Status    : completed
 Created SQL Firewall Rule rule1
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Sql/servers/jasonr3labs/firewallRules/rule1
   Status    : completed
 Created Storage Container sc1
   ID    : sc1
   Status    : completed
 Created Loadbalancer http
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/loadBalancers/lb/probes/http
   Status    : completed
 Created Network Interface web-1
   IP : 10.0.1.4
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/networkInterfaces/web-1
   Status : completed
 Created Network Interface web-2
   IP : 10.0.1.5
   ID : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/networkInterfaces/web-2
   Status : completed
 Created Loadbalancer http
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Network/loadBalancers/lb/loadBalancingRules/http
   Status    : completed
 Created Virtual Machine web-1
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Compute/virtualMachines/web-1
   Status    : completed
 Created Virtual Machine web-2
   ID    : /subscriptions/ab37259d-b5cf-4061-9241-95ac9c6fee1d/resourceGroups/az-test/providers/Microsoft.Compute/virtualMachines/web-2
   Status    : completed
SUCCESS: rules successfully applied
➜  demo ernest service list
+---------+--------+----------+-----------------------------+-------+
|  NAME   | STATUS | ENDPOINT |         LAST BUILD          | USER  |
+---------+--------+----------+-----------------------------+-------+
| az-test | done   |          | 2017-06-07T15:38:32.100302Z | user1 |
| demo    | done   |          | 2017-06-07T15:37:54.388892Z | user1 |
+---------+--------+----------+-----------------------------+-------+
➜  demo ernest service info az-test
Name : az-test
Status : done
Date : 2017-06-07 15:38:32.100302 +0000 UTC
Load Balancers:
+------+----+
| NAME | IP |
+------+----+
| lb   |    |
+------+----+
Virtual Machines:
+-------+----------------+------------+
| NAME  |   PUBLIC IP    | PRIVATE IP |
+-------+----------------+------------+
| web-1 | 52.233.137.179 | 10.0.1.4   |
| web-2 | 52.232.44.210  | 10.0.1.5   |
+-------+----------------+------------+
SQL Databases:
+------+-------------+
| NAME | SERVER NAME |
+------+-------------+
| mydb |             |
+------+-------------+
➜  demo
```
